// Generated by gencpp from file freefloating_gazebo/ControlTypeResponse.msg
// DO NOT EDIT!


#ifndef FREEFLOATING_GAZEBO_MESSAGE_CONTROLTYPERESPONSE_H
#define FREEFLOATING_GAZEBO_MESSAGE_CONTROLTYPERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace freefloating_gazebo
{
template <class ContainerAllocator>
struct ControlTypeResponse_
{
  typedef ControlTypeResponse_<ContainerAllocator> Type;

  ControlTypeResponse_()
    {
    }
  ControlTypeResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::freefloating_gazebo::ControlTypeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::freefloating_gazebo::ControlTypeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ControlTypeResponse_

typedef ::freefloating_gazebo::ControlTypeResponse_<std::allocator<void> > ControlTypeResponse;

typedef boost::shared_ptr< ::freefloating_gazebo::ControlTypeResponse > ControlTypeResponsePtr;
typedef boost::shared_ptr< ::freefloating_gazebo::ControlTypeResponse const> ControlTypeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::freefloating_gazebo::ControlTypeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::freefloating_gazebo::ControlTypeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace freefloating_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::freefloating_gazebo::ControlTypeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::freefloating_gazebo::ControlTypeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::freefloating_gazebo::ControlTypeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::freefloating_gazebo::ControlTypeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::freefloating_gazebo::ControlTypeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::freefloating_gazebo::ControlTypeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::freefloating_gazebo::ControlTypeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::freefloating_gazebo::ControlTypeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::freefloating_gazebo::ControlTypeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "freefloating_gazebo/ControlTypeResponse";
  }

  static const char* value(const ::freefloating_gazebo::ControlTypeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::freefloating_gazebo::ControlTypeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::freefloating_gazebo::ControlTypeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::freefloating_gazebo::ControlTypeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlTypeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::freefloating_gazebo::ControlTypeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::freefloating_gazebo::ControlTypeResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FREEFLOATING_GAZEBO_MESSAGE_CONTROLTYPERESPONSE_H
